# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

AS=/usr/bin/gcc
MM=/usr/bin/gcc
CU=/usr/bin/clang
CXX=/usr/bin/gcc
GC=/usr/bin/go
MXX=/usr/bin/gcc
RC=/home/rm/.cargo/bin/rustc
CC=/usr/bin/gcc

AR=/usr/bin/ar
GCAR=/usr/bin/go
RCAR=/home/rm/.cargo/bin/rustc
SH=/usr/bin/g++
RCSH=/home/rm/.cargo/bin/rustc
LD=/usr/bin/g++
GCLD=/usr/bin/go
RCLD=/home/rm/.cargo/bin/rustc

embedded-utils_LD=/usr/bin/g++
embedded-utils_CC=/usr/bin/gcc

embedded-utils_CCFLAGS=-m64 -fvisibility=hidden -O3 -Iinclude -DNDEBUG
embedded-utils_LDFLAGS=-m64 -s

default:  embedded-utils

all:  embedded-utils

.PHONY: default all  embedded-utils

embedded-utils: build/linux/x86_64/release/embedded-utils
build/linux/x86_64/release/embedded-utils: build/.objs/embedded-utils/linux/x86_64/release/src/containers/list.c.o build/.objs/embedded-utils/linux/x86_64/release/src/main.c.o
	@echo linking.release embedded-utils
	@mkdir -p build/linux/x86_64/release
	$(VV)$(embedded-utils_LD) -o build/linux/x86_64/release/embedded-utils build/.objs/embedded-utils/linux/x86_64/release/src/containers/list.c.o build/.objs/embedded-utils/linux/x86_64/release/src/main.c.o $(embedded-utils_LDFLAGS)

build/.objs/embedded-utils/linux/x86_64/release/src/containers/list.c.o: src/containers/list.c
	@echo compiling.release src/containers/list.c
	@mkdir -p build/.objs/embedded-utils/linux/x86_64/release/src/containers
	$(VV)$(embedded-utils_CC) -c $(embedded-utils_CCFLAGS) -o build/.objs/embedded-utils/linux/x86_64/release/src/containers/list.c.o src/containers/list.c

build/.objs/embedded-utils/linux/x86_64/release/src/main.c.o: src/main.c
	@echo compiling.release src/main.c
	@mkdir -p build/.objs/embedded-utils/linux/x86_64/release/src
	$(VV)$(embedded-utils_CC) -c $(embedded-utils_CCFLAGS) -o build/.objs/embedded-utils/linux/x86_64/release/src/main.c.o src/main.c

clean:  clean_embedded-utils

clean_embedded-utils: 
	@rm -rf build/linux/x86_64/release/embedded-utils
	@rm -rf build/linux/x86_64/release/embedded-utils.sym
	@rm -rf build/.objs/embedded-utils/linux/x86_64/release/src/containers/list.c.o
	@rm -rf build/.objs/embedded-utils/linux/x86_64/release/src/main.c.o

